name: MaceControl
version: '1.0-SNAPSHOT'
main: net.macecontrol.Main
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  macefind:
    description: Find all maces on the server
    usage: /macefind
    permission: macecontrol.macefind
  maceclean:
    description: Clean invalid maces from online players and reset mace data
    usage: /maceclean [confirm]
    permission: macecontrol.maceclean
  macereset:
    description: Reset all mace data
    usage: /macereset [confirm]
    permission: macecontrol.macereset
  macecount:
    description: View or set the mace count
    usage: /macecount [set <value>]
    permission: macecontrol.macecount
  maceset:
    description: Configure mace settings
    usage: /maceset <max|enchantable> <value>
    permission: macecontrol.maceset

permissions:
  macecontrol.macefind:
    description: Allows finding maces on the server
    default: op
  macecontrol.maceclean:
    description: Allows cleaning invalid maces
    default: op
  macecontrol.macereset:
    description: Allows resetting mace data
    default: op
  macecontrol.macecount:
    description: Allows viewing and setting mace count
    default: op
  macecontrol.maceset:
    description: Allows configuring mace settings
    default: op
