name: MaceControl
version: '${version}'
main: net.macecontrol.Main
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  macecontrol:
    description: Manage MaceControl - find, clean (wipe + reset), count and configure maces
    usage: /macecontrol <find|clean|count|set> [args]
    aliases: [ mc ]

permissions:
  macecontrol.find:
    description: Allows finding maces on the server
    default: op
  macecontrol.clean:
    description: Allows wiping all maces and resetting mace data
    default: op
  macecontrol.count:
    description: Allows viewing and setting mace count
    default: op
  macecontrol.set:
    description: Allows configuring mace settings
    default: op