name: MaceControl
version: '1.0-SNAPSHOT'
main: net.macecontrol.Main
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]


commands:
  giveweapon:
    description: Give custom weapons to players
    permission: stupidmacecontrol.giveweapon
    usage: /<command> <player> <weapon>
  setspawn:
    description: Set the server spawn location
    usage: /setspawn
    permission: stupidmacecontrol.setspawn
  spawn:
    description: Teleport to spawn
    usage: /spawn
  macefind:
    description: Find all maces on the server
    usage: /macefind
    permission: stupidmacecontrol.macefind
  maceclean:
    description: Clean invalid maces from online players and reset mace data
    usage: /maceclean [confirm]
    permission: stupidmacecontrol.maceclean
  macereset:
    description: Reset all mace data
    usage: /macereset [confirm]
    permission: stupidmacecontrol.macereset
  macecount:
    description: View or set the mace count
    usage: /macecount [set <0-3>]
    permission: stupidmacecontrol.macecount

permissions:
  stupidmacecontrol.macefind:
    description: Allows finding maces on the server
    default: op
  stupidmacecontrol.maceclean:
    description: Allows cleaning invalid maces and resetting mace data
    default: op
  stupidmacecontrol.macereset:
    description: Allows resetting mace data
    default: op
  stupidmacecontrol.macecount:
    description: Allows viewing/setting mace count
    default: op
  stupidmacecontrol.setspawn:
    description: Allows setting the spawn location
    default: op
  stupidmacecontrol.giveweapon:
    description: Allows giving custom weapons
    default: op