name: MaceControl
version: '1.0-SNAPSHOT'
main: net.macecontrol.Main
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  macefind:
    description: Find all maces on the server
    usage: /macefind
    permission: stupidmacecontrol.macefind
  maceclean:
    description: Clean invalid maces from online players and reset mace data
    usage: /maceclean [confirm]
    permission: stupidmacecontrol.maceclean
  macereset:
    description: Reset all mace data
    usage: /macereset [confirm]
    permission: stupidmacecontrol.macereset
  macecount:
    description: View or set the mace count
    usage: /macecount [set <0-3>]
    permission: stupidmacecontrol.macecount


  stupidmacecontrol.macefind:
    description: Allows finding maces on the server
    default: op

  stupidmacecontrol.maceclean:
    description: Allows cleaning invalid maces
    default: op

  stupidmacecontrol.macereset:
    description: Allows resetting mace data
    default: op

  stupidmacecontrol.macecount:
    description: Allows viewing and setting mace count
    default: op
