name: MaceControl
version: '1.0-SNAPSHOT'
main: net.macecontrol.Main
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]
description: Mace Control with Potion Restrictions

commands:
  macefind:
    description: Find players with maces and show server mace status
    usage: /macefind
    permission: stupidmacecontrol.macefind
  maceclean:
    description: Clean invalid maces from all online players
    usage: /maceclean
    permission: stupidmacecontrol.maceclean

permissions:
  stupidmacecontrol.macefind:
    description: Allows use of /macefind command
    default: op
  stupidmacecontrol.maceclean:
    description: Allows use of /maceclean command
    default: op